language: node_js

node_js:
  - 0.10

env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/angular-templating-build/logs
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987

install:
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce_connect_setup.sh
  - npm install
  - ./node_modules/.bin/bower install
  - ./scripts/wait_for_browser_provider.sh

script:
  - gulp build
  - ./node_modules/.bin/karma start --single-run --browsers SL_Chrome --reporters dots
  - ./scripts/testonsauce.sh

after_script:
  - ./scripts/print_logs.sh
